spring:
  application:
    name: mytest
  mandatory-file-encoding: UTF-8
  http:
    encoding:
      charset: UTF-8
      enabled: true
server:
  port: 8080

myConfig:
  myObject:
    myName: zhangsan
    myAge: 20


